ShapeTracker(views=(View(shape=(1024,
16), strides=(16, 1), offset=0, mask=None, contiguous=True),)), (), dtypes.float,
'METAL'), (ShapeTracker(views=(View(shape=(1024, 7), strides=(7, 1), offset=0,
mask=None, contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL')] !=
st_vars_dtype_device=[(ShapeTracker(views=(View(shape=(1024, 16), strides=(16, 1),
offset=0, mask=None, contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(2048, 7), strides=(7, 1), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(2048,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL'),
(ShapeTracker(views=(View(shape=(1024,), strides=(1,), offset=0, mask=None,
contiguous=True),)), (), dtypes.float, 'METAL')]