repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: uvx isort
      language: system
      types: [python]
      
    - id: ruff
      name: ruff
      entry: uvx ruff check
      language: system
      types: [python] 